#org.gradle.daemon=true
#org.gradle.jvmargs=-Xms128m -Xmx1500m
#org.gradle.configureondemand=false

# Android Java compatibility
#android.useAndroidX=true
#android.enableJetifier=true
#android.suppressUnsupportedCompileSdk=31
#android.overridePathCheck=true

# JVM arguments for Java 21 compatibility
#org.gradle.jvmargs=-Xms128m -Xmx1500m --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.nio.channels=ALL-UNNAMED --add-opens=java.base/java.nio.channels.spi=ALL-UNNAMED --add-opens=java.base/java.nio.channels.spi=ALL-UNNAMED --add-opens=java.base/java.nio.channels.spi=ALL-UNNAMED
